<a href="https://colab.research.google.com/github/Legendkiller9855/GENRATIVE_AI/blob/main/Assignment_9_Numpy(Mathematical_%26_Staistical_Operations).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#TASK - 1 : Creating Numpy Arrays
import numpy as np
array_1 = np.arange(1,11)

array_2 = np.arange(1,10).reshape(3,3)

array_3 = np.array([10,20,30,40,50])

#Arrays
print(array_1)
print(array_2)
print(array_3)

#Shape of each array
print(array_1.shape)
print(array_2.shape)
print(array_3.shape)

#Data type of each array
print(array_1.dtype)
print(array_2.dtype)
print(array_3.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30 40 50]
(10,)
(3, 3)
(5,)
int64
int64
int64


In [20]:
#TASK - 2 : Important Mathematical Operations
import numpy as np
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

#Mathematical Operations
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A ** 2)

#Optional  :
array_1 = np.add(A,B)
print(array_1)


array_2 = np.subtract(A,B)
print(array_2)


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]
[11 22 33 44]
[ 9 18 27 36]


In [ ]:
#TASK - 3 : Important Numpy Mathematical Formulas
import numpy as np
values = np.array([2,4,6,8,10])
