<a href="https://colab.research.google.com/github/Legendkiller9855/GENRATIVE_AI/blob/main/Assignment_9_Numpy(Mathematical_%26_Staistical_Operations).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#TASK - 1 : Creating Numpy Arrays
import numpy as np
array_1 = np.arange(1,11)

array_2 = np.arange(1,10).reshape(3,3)

array_3 = np.array([10,20,30,40,50])

#Arrays
print(array_1)
print(array_2)
print(array_3)

#Shape of each array
print(array_1.shape)
print(array_2.shape)
print(array_3.shape)

#Data type of each array
print(array_1.dtype)
print(array_2.dtype)
print(array_3.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30 40 50]
(10,)
(3, 3)
(5,)
int64
int64
int64


In [ ]:
#TASK - 2 : Important Mathematical Operations
import numpy as np
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

#Mathematical Operations
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A ** 2)

#Optional  :
array_1 = np.add(A,B)
print(array_1)


array_2 = np.subtract(A,B)
print(array_2)


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]
[11 22 33 44]
[ 9 18 27 36]


In [8]:
#TASK - 3 : Important Numpy Mathematical Formulas
import numpy as np
values = np.array([2,4,6,8,10])
square_root = np.sqrt(values)
print(square_root)

exponential_value = np.exp(values)
print(exponential_value)

logarithm_value = np.log(values)
print(logarithm_value)

sum_values = np.sum(values)
print(sum_values)

sum_cumulative_value = np.cumsum(values)
print(sum_cumulative_value)

[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
30
[ 2  6 12 20 30]


In [12]:
#TASK - 4 : Aggregation Operations
import numpy as np
data = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(data)

row_wise_sum = np.sum(data,axis = 1)
print(row_wise_sum)


column_wise_sum = np.sum(data,axis = 0)
print(column_wise_sum)

minimum_value = np.min(data)
print(minimum_value)


maximum_value = np.max(data)
print(maximum_value)

mean_value = np.mean(data)
print(mean_value)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[ 60 150 240]
[120 150 180]
10
90
50.0


In [17]:
#TASK - 5 : Staistical Operations(Core Focus)
import numpy as np
marks = np.array([78,85,90,66,72,88,95,60])
print(marks)

mean_value = np.mean(marks)
print(mean_value)


median_value = np.median(marks)
print(median_value)


variance_value = np.var(marks)
print(variance_value)


standard_deviation_value = np.std(marks)
print(standard_deviation_value)

min_value = np.min(marks)
print(min_value)

max_value = np.max(marks)
print(max_value)

range_value = (max_value - min_value)
print(range_value)

[78 85 90 66 72 88 95 60]
79.25
81.5
134.1875
11.583932838203095
60
95
35


In [27]:
#TASK - 6 : Percentiles & Sorting
import numpy as np
marks = np.array([78,85,90,66,72,88,95,60])
print(marks)

sorted_array = np.sort(marks)
print(sorted_array)

percentile_25 = np.percentile(marks,25)
print(percentile_25)

percentile_50 = np.percentile(marks,50)
print(percentile_50)

percentile_75 = np.percentile(marks,75)
print(percentile_75)

mean_marks = np.mean(marks)
print(mean_marks)

list_marks = []
for i in marks :
  if i > mean_marks:
    list_marks.append(int(i))
print(list_marks)

count_marks = len(list_marks)
print(count_marks)

[78 85 90 66 72 88 95 60]
[60 66 72 78 85 88 90 95]
70.5
81.5
88.5
79.25
[85, 90, 88, 95]
4


In [30]:
#TASK - 7 : Mini Use Case : Sales Analysis
import numpy as np
sales = np.array([1200,1500,900,2000,1800,1700,1600])

total_weekly_sales = np.sum(sales)
print(total_weekly_sales)

average_daily_sales = np.mean(sales)
print(average_daily_sales)

highest_sales_day = np.max(sales)
print(highest_sales_day)

lowest_sales_day = np.min(sales)
print(lowest_sales_day)

standard_deviation_sales = np.std(sales)
print(standard_deviation_sales)

lists = []
for i in sales:
  if i > average_daily_sales :
    lists.append(int(i))

print(lists)

print(len(lists))

10700
1528.5714285714287
2000
900
345.2298849598449
[2000, 1800, 1700, 1600]
4
