<a href="https://colab.research.google.com/github/Legendkiller9855/GENRATIVE_AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**


**Numpy --> Numpy is a fundamental package for scientific computing in python.It is a python library that provides a multi-dimensional array object and various derived objects such as masked arrays or matrices and an assortment of routines for fast operations on Arrays including mathematical , logical , shape manipulation , sorting , selecting , I/O ,Discrete Fourier Transform , Basic Linear Algebra , stastical operations , Random simulation , etc.**

**At the core of the numpy package is the ndimensional array object.**

**Why NUMPY :**



1.   2008-2009, Data Science --> Matlab and R language were used(python was not in use)
2.   Data Types in Python --> List & Dictionary --> Slow
3.   Syntax --> Python --> Easy
4.   We needed speed and less memory to work with the huge amount of data.
5.   Numpy --> C Language --> Wrapped --> Python Language
6.   Numpy --> Syntax --> Easy for Beginners --> Performing Scientific Calculations --> Creating Multi-Dimensional Arrays --> Speed is faster for applying operations --> Less Memory.
7.   Libraries like Scikit-Learn , tensorflow and Pytorch require input data in Numpy arrays or tensors.



**Numpy arrays vs Python Sequences**

*  Numpy arrays have a fixed size at creation , unlike python lists which grow dynamically.

*  Changing the size of an ndim array will create a new array and delete the original.

*  The elements in a Numpy Array are required to be of the same data type and thus will be of the same size in memory.

*  Numpy Arrays facilitates advanced mathematical and other types of operations on large number of data.Typically , such operations are executed more efficiently with less code than is possible using python's built-in sequences.



In [2]:
#1-D Array
import numpy as np
numpy_array = np.array([1,2,3,4,5,6]) #1-D Array
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


**Number of rows & columns must be same in the 2-D Array.**

In [6]:
#2-D Array
import numpy as np
two_D_array = np.array([[1,2,3],[4,5,6]]) #2-D Array
print(two_D_array)
print(type(two_D_array))

two_D_extended_array = np.array([[1,2,3],[4,5,6],[7,8,9]]) #2-D Array
print(two_D_extended_array)
print(type(two_D_extended_array))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
#3-D Array
import numpy as np
three_D_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(three_D_array)
print(type(three_D_array))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
<class 'numpy.ndarray'>


**np.array() --> Used for creating multi-dimensional arrays.**

**np.array() --> Stores data of same data type only.**

**dtype() parameter --> Which can help us out with deciding about the size of the data we are going to store inside our array.**

In [8]:
#Specify the memory allocated or used by each value
import numpy as np
array = np.array([1,2,3,4],dtype = np.int32)
print(array)

# array = np.array([1,2,3,4], dtype=np.int32)

# creates a NumPy array using the NumPy library in Python.

# np.array() is a function used to create an array.
# [1, 2, 3, 4] is a Python list that provides the elements of the array.
# dtype=np.int32 specifies the data type of each element in the array as a 32-bit integer.

# This means:

# All elements (1, 2, 3, 4) will be stored as 32-bit integers.
# The array will be more memory-efficient and consistent in type.

# Result:

# A one-dimensional NumPy array with 4 elements.
# Shape of the array is (4,)
# Data type (dtype) is int32.

#Other options int64,float32,float64,bool etc.

[1 2 3 4]


In [23]:
# Import NumPy library
import numpy as np


# Create a normal Python list
list1 = []

# Loop from 0 to 14 (15 elements total)
for i in range(15):
  list1.append(i)   # Add each number to the list

# Print the Python list
print(list1)


# NumPy arange(start, stop)
# Creates an array from 3 to 14 (15 is excluded)
print(np.arange(3,15))   # Continuous array


# NumPy arange(start, stop, step)
# Starts from 3, ends before 15, step = 2
# Skips numbers → output: 3,5,7,9,11,13
print(np.arange(3,15,2))


# Create NumPy array from 2 to 15
arange_data = np.arange(2,16)   # total elements = 14


# reshape(rows, columns)
# ⚠️ reshape does NOT change data, only changes structure
# Condition: rows × columns = total elements
# Here: 2 × 7 = 14 ✔
arange_data.reshape(2,7)


# Create array from 2 to 16 (step = 2)
# Output: [2,4,6,8,10,12,14,16] → total 8 elements
# reshape into 2 rows and 4 columns → 2 × 4 = 8 ✔
print(np.arange(2,17,2).reshape(2,4))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  5  7  9 11 13]
[[ 2  4  6  8]
 [10 12 14 16]]


**arange() --> It helps us out with providing the values over a certain range.**

**np.reshape() --> It helps us out with changing the shape of the array as per our needs.**

In [26]:
#Creating Array with all values either as 1 or 0.
import numpy as np
print(np.ones((4,4))) #Used to create an array with all values as one and of desired shape(row,column)

print(np.zeros((4,4),dtype = int)) #Used to create an array with all values as zero and of desired shape(row,column) and dtype = int is used to keep all the data types as integer data types.


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**random() --> It helps us out with generating any random values from 0 to 1 inside our matrix.**

In [36]:
#To create an array with all values as randomised
import numpy as np

# np.random.random()
# Generates random FLOAT values between 0 and 1
# (3,4) → 3 rows, 4 columns
print(np.random.random((3,4)))

#We cannot directly the data type to be integer but can use other method as:

# ✅ Correct syntax of randint:
# np.random.randint(low, high, size)

# Example:
# Generate integers from 0 to 9 (high is excluded)
# size = (2,4) → 2 rows, 4 columns
print(np.random.randint(0, 10, (2,4)))


[[5.81319717e-01 6.78441812e-01 9.48068244e-01 5.31390608e-01]
 [1.40468845e-01 5.39556773e-01 1.90206712e-02 9.19290211e-01]
 [1.23858576e-04 2.86801236e-02 3.90153275e-01 4.84316699e-01]]
[[7 9 2 0]
 [5 3 1 6]]


**Identity() --> It helps us out with creating the matrix as an Identity Matrix.(Square Matrix --> Rows = Columns)**

In [28]:
#To create identity matrix
import numpy as np
print(np.identity(3)) #3 is the number of rows and columns to be included in the matrix
#Identity matrix is the one in which the primary diagonals values are 1 and rest all are zero.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**linespace() --> It makes sure that every value with the given range is going to have the similar distance from each other.**

In [35]:
# Import NumPy library
import numpy as np


# np.linspace(start, stop, num)
# Generates 'num' evenly spaced values between start and stop (inclusive)

# Here:
# start = -10
# stop = 10
# num = 10 (total number of values)

print(np.linspace(-10, 10, 10))

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


#Attributes


*   ndim() --> ndim stands for n dimension.

*   shape() --> It provides us with the idea about the rows,columns in our dataset or in array.

*   size() --> Tells us the total number of elements present inside our datset or array.

*   itemsize() --> Provides us with the idea about the size of a unique element inside our array in bytes.

*   dtype() --> It provides us with the idea about the type of every item inside our array.



In [41]:
#ndim()
import numpy as np
array = np.array([1,2,3,4,5])
print(array)
print(array.ndim)

two_D_array = np.array([[1,2],[3,4],[1,2],[5,6]])
print(two_D_array)
print(two_D_array.ndim)

three_D_array = np.array([[[1,2],[3,4]],[[1,2],[5,6]]])
print(three_D_array)
print(three_D_array.ndim)

[1 2 3 4 5]
1
[[1 2]
 [3 4]
 [1 2]
 [5 6]]
2
[[[1 2]
  [3 4]]

 [[1 2]
  [5 6]]]
3


In [43]:
#shape()
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
print(array.shape)

array2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array2)
print(array2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [48]:
#size() & itemsize()
import numpy as np
array_elements = np.arange(5,57)
print(array_elements)
print(array_elements.size)

array1 = np.array([[1,2],[3,4],[5,6]]).itemsize
print(array1)

array2 = np.array([[1,2],[3,4],[5,6]],dtype = np.int32).itemsize
print(array2)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56]
52
8
4


In [50]:
#dtype()
import numpy as np
array1 = np.array([[1,2,3],[4,5,6]]).dtype
print(array1)

int64
